In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=10000


In [9]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4323, 3669, 3024, 815],
 [4323, 3669, 3024, 1364],
 [4323, 1460, 3024, 7755],
 [1792, 236, 2157, 2485, 1913],
 [1792, 236, 2157, 2485, 7907],
 [9520, 4323, 8052, 3024, 5631],
 [1691, 1702, 7706, 2485]]

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
sent_length=8
embedd_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedd_doc

array([[   0,    0,    0,    0, 4323, 3669, 3024,  815],
       [   0,    0,    0,    0, 4323, 3669, 3024, 1364],
       [   0,    0,    0,    0, 4323, 1460, 3024, 7755],
       [   0,    0,    0, 1792,  236, 2157, 2485, 1913],
       [   0,    0,    0, 1792,  236, 2157, 2485, 7907],
       [   0,    0,    0, 9520, 4323, 8052, 3024, 5631],
       [   0,    0,    0,    0, 1691, 1702, 7706, 2485]])

In [14]:
## feature rep
dim=10


In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedd_doc)

1/1 [==============================] - 0s 355ms/step


array([[[ 0.03331883, -0.02552485,  0.02375528, -0.04569726,
         -0.01307661,  0.01176578, -0.01913533, -0.00345794,
         -0.03517528,  0.04281983],
        [ 0.03331883, -0.02552485,  0.02375528, -0.04569726,
         -0.01307661,  0.01176578, -0.01913533, -0.00345794,
         -0.03517528,  0.04281983],
        [ 0.03331883, -0.02552485,  0.02375528, -0.04569726,
         -0.01307661,  0.01176578, -0.01913533, -0.00345794,
         -0.03517528,  0.04281983],
        [ 0.03331883, -0.02552485,  0.02375528, -0.04569726,
         -0.01307661,  0.01176578, -0.01913533, -0.00345794,
         -0.03517528,  0.04281983],
        [-0.03225316, -0.00759267,  0.01056589, -0.01578066,
          0.02603597, -0.00166776,  0.04460016,  0.01410324,
          0.02158583, -0.03575778],
        [-0.0413056 , -0.02118909,  0.01676679, -0.04306516,
         -0.00577388, -0.02857809,  0.0261464 ,  0.00859871,
          0.04453463,  0.01246988],
        [-0.01194061,  0.0035476 , -0.03370949,  0.0

In [19]:
embedd_doc[0]

array([   0,    0,    0,    0, 4323, 3669, 3024,  815])